(* predefined "lists" *)
DIGIT       = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;

(* tokens *)
number      = DIGIT , { DIGIT } , [ '.' , DIGIT , { DIGIT } ] ;
eof         = ? end of file ? ;

(* nodes *)
Expression  = Term , { ( '+' | '-' ) , Term } ;
Term        = Factor , { ( '*' | '/' | '%' ) , Factor } ;
Factor      = ( '+' | '-' ) , Factor
            | '('  , Expression , ')'
            | number ;
